"use client";
import { useState } from "react";
import { ArrowLeft, BadgeCheck, Bell, BriefcaseBusiness, Check, ChevronLeft, CircleDollarSign, Globe2, Menu, Search, ShieldCheck, Sparkles, WalletCards, X } from "lucide-react";

const jobs = [
  { title: "مصمم تجربة مستخدم لتطبيق صحي", company: "نمو للرعاية", price: "3,500 – 5,000 ر.س", tag: "تصميم", time: "منذ ساعتين", color: "bg-violet-100 text-violet-700" },
  { title: "مطور Next.js لمنصة تجارة إلكترونية", company: "أفق الرقمية", price: "6,000 – 9,000 ر.س", tag: "تطوير", time: "منذ 4 ساعات", color: "bg-sky-100 text-sky-700" },
  { title: "كاتب محتوى تقني باللغة العربية", company: "مِداد", price: "1,800 – 2,500 ر.س", tag: "كتابة", time: "منذ 6 ساعات", color: "bg-amber-100 text-amber-700" }
];
const categories = ["تطوير وبرمجة", "تصميم وإبداع", "تسويق ومبيعات", "كتابة وترجمة", "أعمال واستشارات"];

export default function Home() {
 const [modal, setModal] = useState(false); const [english, setEnglish] = useState(false);
 const label = english ? {jobs:"Jobs", services:"Services", categories:"Categories", login:"Sign in", hero:"Work with confidence.", sub:"A trusted space where exceptional talent meets ambitious projects.", browse:"Browse opportunities", post:"Post a project", active:"Active opportunities", talents:"Verified talents"} : {jobs:"الوظائف", services:"الخدمات", categories:"التصنيفات", login:"تسجيل الدخول", hero:"مساحتك للعمل الذي تستحقه.", sub:"منصة موثوقة تجمع الكفاءات الاستثنائية بالمشاريع الطموحة، بكل شفافية وأمان.", browse:"تصفح الفرص", post:"أضف مشروعك", active:"فرصة نشطة", talents:"كفاءة موثّقة"};
 return <main className={english ? "" : ""} dir={english ? "ltr" : "rtl"}>
  <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5">
   <div className="flex items-center gap-10"><div className="flex items-center gap-2 text-2xl font-black text-brand"><span className="grid h-9 w-9 place-items-center rounded-xl bg-brand text-xl text-white">ك</span> كفاءات</div><div className="hidden gap-7 text-sm font-bold text-slate-600 md:flex"><a href="#jobs">{label.jobs}</a><a href="#services">{label.services}</a><a href="#categories">{label.categories}</a></div></div>
   <div className="flex items-center gap-3"><button onClick={()=>setEnglish(!english)} className="rounded-lg p-2 text-slate-600 hover:bg-white" aria-label="تغيير اللغة"><Globe2 size={19}/></button><button className="hidden rounded-xl border border-brand px-4 py-2 text-sm font-bold text-brand sm:block">{label.login}</button><button onClick={()=>setModal(true)} className="rounded-xl bg-brand px-4 py-2 text-sm font-bold text-white shadow-lg shadow-brand/20">{label.post}</button><Menu className="md:hidden"/></div>
  </nav>
  <section className="relative overflow-hidden"><div className="absolute right-[-5rem] top-0 h-72 w-72 rounded-full bg-teal-100 blur-3xl"/><div className="mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-14 lg:grid-cols-[1.1fr_.9fr] lg:items-center">
   <div className="relative"><div className="mb-6 inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-bold text-brand shadow-sm"><Sparkles size={16}/> مجتمع مهني موثوق</div><h1 className="max-w-2xl text-4xl font-black leading-tight text-ink sm:text-6xl">{label.hero}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">{label.sub}</p><div className="mt-8 flex flex-wrap gap-3"><button className="flex items-center gap-2 rounded-xl bg-brand px-6 py-3.5 font-bold text-white" onClick={()=>document.getElementById("jobs")?.scrollIntoView()}>{label.browse}<ArrowLeft size={18}/></button><button onClick={()=>setModal(true)} className="rounded-xl border border-slate-300 bg-white px-6 py-3.5 font-bold text-ink">{label.post}</button></div><div className="mt-12 flex gap-8"><Stat n="+12,000" t={label.active}/><Stat n="+8,500" t={label.talents}/><Stat n="4.9/5" t="تقييم المجتمع"/></div></div>
   <div className="relative rounded-[2rem] bg-ink p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between text-white"><span className="font-bold">فرص مقترحة لك</span><Bell size={18}/></div>{jobs.slice(0,2).map(j=><div key={j.title} className="mb-3 rounded-2xl bg-white p-4"><div className="flex items-start justify-between"><span className={`rounded-lg px-2 py-1 text-xs font-bold ${j.color}`}>{j.tag}</span><BadgeCheck className="text-brand" size={18}/></div><p className="mt-3 font-bold text-ink">{j.title}</p><p className="mt-1 text-sm text-slate-500">{j.company}</p><div className="mt-3 flex justify-between text-sm font-bold"><span className="text-brand">{j.price}</span><span className="text-slate-400">{j.time}</span></div></div>)}<div className="mt-5 flex items-center gap-2 rounded-xl border border-teal-400/30 bg-teal-400/10 p-3 text-sm text-teal-100"><ShieldCheck size={20}/> مدفوعاتك محمية في الضمان</div></div>
  </div></section>
  <section id="categories" className="bg-white py-10"><div className="mx-auto max-w-7xl px-5"><p className="text-sm font-bold text-brand">استكشف مجالاتك</p><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-5">{categories.map((c,i)=><button key={c} className="rounded-2xl border border-slate-100 p-4 text-right text-sm font-bold hover:border-brand hover:text-brand"><span className="mb-3 grid h-9 w-9 place-items-center rounded-xl bg-sand text-brand"><BriefcaseBusiness size={18}/></span>{c}<ChevronLeft className="float-left" size={16}/></button>)}</div></div></section>
  <section id="jobs" className="mx-auto max-w-7xl px-5 py-16"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-bold text-brand">أحدث الفرص</p><h2 className="mt-2 text-3xl font-black">مشاريع تستحق مهاراتك</h2></div><button className="flex items-center gap-1 font-bold text-brand">عرض كل الوظائف <ArrowLeft size={17}/></button></div><div className="mt-8 grid gap-4 lg:grid-cols-3">{jobs.map(j=><article key={j.title} className="rounded-2xl bg-white p-5 shadow-card"><div className="flex justify-between"><span className={`rounded-lg px-2.5 py-1 text-xs font-bold ${j.color}`}>{j.tag}</span><span className="text-xs text-slate-400">{j.time}</span></div><h3 className="mt-5 text-lg font-bold">{j.title}</h3><p className="mt-2 text-sm text-slate-500">{j.company} <BadgeCheck className="inline text-brand" size={15}/></p><div className="my-5 border-t"/><div className="flex items-center justify-between"><span className="font-bold text-brand">{j.price}</span><button onClick={()=>setModal(true)} className="rounded-lg bg-sand px-3 py-2 text-sm font-bold">عرض التفاصيل</button></div></article>)}</div></section>
  <section id="services" className="bg-ink py-14 text-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 md:grid-cols-3"><Feature icon={<ShieldCheck/>} title="ضمان كامل للمدفوعات" text="تبقى أموالك في حساب الضمان حتى تأكيد استلام العمل."/><Feature icon={<BadgeCheck/>} title="كفاءات موثّقة" text="هوية ومهارات موثقة لتتعاون بثقة واطمئنان."/><Feature icon={<WalletCards/>} title="محفظة مرنة" text="تابع رصيدك واسحب أرباحك بالطريقة التي تناسبك."/></div></section>
  {modal && <Paywall close={()=>setModal(false)}/>} 
 </main>
}
function Stat({n,t}:{n:string,t:string}) { return <div><b className="block text-xl">{n}</b><span className="text-sm text-slate-500">{t}</span></div> }
function Feature({icon,title,text}:{icon:React.ReactNode,title:string,text:string}) { return <div><div className="mb-4 grid h-11 w-11 place-items-center rounded-xl bg-brand">{icon}</div><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{text}</p></div> }
function Paywall({close}:{close:()=>void}) { return <div className="fixed inset-0 z-20 grid place-items-center bg-ink/60 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-7 shadow-2xl"><button onClick={close} className="float-left text-slate-500"><X/></button><div className="grid h-12 w-12 place-items-center rounded-2xl bg-teal-100 text-brand"><CircleDollarSign/></div><h2 className="mt-5 text-2xl font-black">فعّل اشتراكك وابدأ الآن</h2><p className="mt-3 leading-7 text-slate-600">هذه الخطوة متاحة للأعضاء المشتركين فقط. اختر الخطة المناسبة وادخل عالم الفرص بثقة.</p><div className="my-5 rounded-2xl border-2 border-brand bg-teal-50 p-4"><div className="flex justify-between"><b>اشتراك كفاءات</b><b className="text-brand">10 ر.س / شهرياً</b></div><p className="mt-2 text-sm text-slate-500"><Check className="inline text-brand" size={16}/> تقديم وطلبات غير محدودة</p></div><button onClick={close} className="w-full rounded-xl bg-brand py-3 font-bold text-white">اشترك بأمان</button><p className="mt-3 text-center text-xs text-slate-400">دفع مشفّر وآمن · لا نحفظ بيانات بطاقتك</p></div></div> }
